
# Create a new account
POST http://localhost:3000/account
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# Authenticate with email password
POST http://localhost:3000/sessions/password
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# Get authenticated user profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYWNmMWQzZS1mMjMwLTQxODgtODQzNC1kMDQxOGE4NDdhODkiLCJpYXQiOjE3MTQ2NTg5MzgsImV4cCI6MTcxNTI2MzczOH0.h1vFvTNjzMEn56Qks83LYk7hYpIcbYtUGOjAt2jEzRQ


###

# Request password recover
POST http://localhost:3000/password/recover
Content-Type: application/json

{
  "email": "johndoe@example.com"
}

###

# Reset password
POST http://localhost:3000/password/reset
Content-Type: application/json

{
  "code": "6f88274f-ce9d-4186-8171-2864ebe699b2",
  "newPassword": "123456"
}

###
# Authenticate with Github (Simulate front-ent processes)
#GET https://github.com/login/oauth/authorize?client_id=Ov23liFUEDNZIF1m1nwL&redirect_uri=http://localhost:3000/api/auth/callback&scope=user:email

# Authenticate with Github
POST http://localhost:3000/sessions/github
Content-Type: application/json

{
  "code": "50893c073aac51a88a73"
}