
# Create a new account
POST http://localhost:3000/account
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# Authenticate with email password
POST http://localhost:3000/sessions/password
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# Get authenticated user profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmRjZWVmYS05MDg3LTQwNGEtOGQ2YS00ZjljOTkxYjg1MTYiLCJpYXQiOjE3MTQ3NDg5MzksImV4cCI6MTcxNTM1MzczOX0.xhMgClXtPi8DEUegI1zO21wSxabRAFym0xXtVEIaEhM


###

# Request password recover
POST http://localhost:3000/password/recover
Content-Type: application/json

{
  "email": "johndoe@example.com"
}

###

# Reset password
POST http://localhost:3000/password/reset
Content-Type: application/json

{
  "code": "6f88274f-ce9d-4186-8171-2864ebe699b2",
  "newPassword": "123456"
}

###
# Authenticate with Github (Simulate front-ent processes)
#GET https://github.com/login/oauth/authorize?client_id=Ov23liFUEDNZIF1m1nwL&redirect_uri=http://localhost:3000/api/auth/callback&scope=user:email

# Authenticate with Github
POST http://localhost:3000/sessions/github
Content-Type: application/json

{
  "code": "50893c073aac51a88a73"
}

###

# Create a new organization
POST http://localhost:3000/organizations
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmRjZWVmYS05MDg3LTQwNGEtOGQ2YS00ZjljOTkxYjg1MTYiLCJpYXQiOjE3MTQ3NDU0OTIsImV4cCI6MTcxNTM1MDI5Mn0.qJNOOSc_DjsyIiAlu-FjR2E1ddp6ZUNbYVrLwBDcvcA

{
   "name": "my org2",
   "domain": "my-org2",
   "avatarUrl": "https://avatars.githubusercontent.com/u/56413810"
}

###

# Get user membership on given organization
GET http://localhost:3000/organizations/my-org2/membership
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmRjZWVmYS05MDg3LTQwNGEtOGQ2YS00ZjljOTkxYjg1MTYiLCJpYXQiOjE3MTQ3NDg5MzksImV4cCI6MTcxNTM1MzczOX0.xhMgClXtPi8DEUegI1zO21wSxabRAFym0xXtVEIaEhM


###

# List authenticated user organizations
GET http://localhost:3000/organizations
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzBjZDBlMC1lMzRmLTRlNDAtYTA3OS03OWNkZTM2OTQ1ZGMiLCJpYXQiOjE3MTUwMDYzOTksImV4cCI6MTcxNTYxMTE5OX0.lGRXh8staVwA_zfO7fSorB_qZIjc5ZnjwiELxa3_MW8

###

# Get organization of an authenticated user by slug
GET http://localhost:3000/organizations/my-org2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmRjZWVmYS05MDg3LTQwNGEtOGQ2YS00ZjljOTkxYjg1MTYiLCJpYXQiOjE3MTQ3NDU0OTIsImV4cCI6MTcxNTM1MDI5Mn0.qJNOOSc_DjsyIiAlu-FjR2E1ddp6ZUNbYVrLwBDcvcA

###

# Update an orginizations data
PUT http://localhost:3000/organizations/my-org2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmRjZWVmYS05MDg3LTQwNGEtOGQ2YS00ZjljOTkxYjg1MTYiLCJpYXQiOjE3MTQ3NDU0OTIsImV4cCI6MTcxNTM1MDI5Mn0.qJNOOSc_DjsyIiAlu-FjR2E1ddp6ZUNbYVrLwBDcvcA
Content-Type: application/json

{
    "name": "org-2",
    "avatarUrl": "",
    "domain": "",
    "shouldAttachUsersByDomain": false
}

###

# Delete an organization
DELETE http://localhost:3000/organizations/my-org2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmRjZWVmYS05MDg3LTQwNGEtOGQ2YS00ZjljOTkxYjg1MTYiLCJpYXQiOjE3MTQ3NDU0OTIsImV4cCI6MTcxNTM1MDI5Mn0.qJNOOSc_DjsyIiAlu-FjR2E1ddp6ZUNbYVrLwBDcvcA

###

# Transfer organization ownership
PATCH http://localhost:3000/organizations/my-org2/owner
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmRjZWVmYS05MDg3LTQwNGEtOGQ2YS00ZjljOTkxYjg1MTYiLCJpYXQiOjE3MTQ3NDU0OTIsImV4cCI6MTcxNTM1MDI5Mn0.qJNOOSc_DjsyIiAlu-FjR2E1ddp6ZUNbYVrLwBDcvcA
Content-Type: application/json

{
  "tranferToUserId": ""
}

###

# Create a new project
POST http://localhost:3000/organizations/my-organization-admin/projects
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzBjZDBlMC1lMzRmLTRlNDAtYTA3OS03OWNkZTM2OTQ1ZGMiLCJpYXQiOjE3MTUwMDYzOTksImV4cCI6MTcxNTYxMTE5OX0.lGRXh8staVwA_zfO7fSorB_qZIjc5ZnjwiELxa3_MW8
Content-Type: application/json

{
  "name": "my first project",
  "description": "some fake description for my project"
}

###

# Delete a project
DELETE http://localhost:3000/organizations/my-organization-admin/projects/my-first-project
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzBjZDBlMC1lMzRmLTRlNDAtYTA3OS03OWNkZTM2OTQ1ZGMiLCJpYXQiOjE3MTUwMDYzOTksImV4cCI6MTcxNTYxMTE5OX0.lGRXh8staVwA_zfO7fSorB_qZIjc5ZnjwiELxa3_MW8
Content-Type: application/json

###

# Get project details
GET http://localhost:3000/organizations/my-organization-admin/projects/my-first-project
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzBjZDBlMC1lMzRmLTRlNDAtYTA3OS03OWNkZTM2OTQ1ZGMiLCJpYXQiOjE3MTUwMDYzOTksImV4cCI6MTcxNTYxMTE5OX0.lGRXh8staVwA_zfO7fSorB_qZIjc5ZnjwiELxa3_MW8

###

# Get project details
GET http://localhost:3000/organizations/my-organization-admin/projects
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzBjZDBlMC1lMzRmLTRlNDAtYTA3OS03OWNkZTM2OTQ1ZGMiLCJpYXQiOjE3MTUwMDYzOTksImV4cCI6MTcxNTYxMTE5OX0.lGRXh8staVwA_zfO7fSorB_qZIjc5ZnjwiELxa3_MW8

###

# Update projects
PUT http://localhost:3000/organizations/my-organization-admin/projects/my-first-project
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzBjZDBlMC1lMzRmLTRlNDAtYTA3OS03OWNkZTM2OTQ1ZGMiLCJpYXQiOjE3MTUwMDYzOTksImV4cCI6MTcxNTYxMTE5OX0.lGRXh8staVwA_zfO7fSorB_qZIjc5ZnjwiELxa3_MW8
Content-Type: application/json


{
  "name": "my first project - updated",
  "description": "some fake description for my project - updated"
}

###

# Get organization members
GET http://localhost:3000/organizations/my-organization-admin/members
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzBjZDBlMC1lMzRmLTRlNDAtYTA3OS03OWNkZTM2OTQ1ZGMiLCJpYXQiOjE3MTUwMDYzOTksImV4cCI6MTcxNTYxMTE5OX0.lGRXh8staVwA_zfO7fSorB_qZIjc5ZnjwiELxa3_MW8

